const data = [
    {
        id: 1,
        name: 'Ароматный круассан',
        img: 'img/item1.jpg',
        price: 3.45,
        store: 10,
        rating: 4.56,
        isNew: true,
        isPopular: true,
    },
    {
        id: 2,
        name: 'Булочка с корицей',
        img: 'img/item2.png',
        price: 2.97,
        store: 3,
        rating: 4.89,
        isNew: true,
        isPopular: false,
    },
    {
        id: 3,
        name: 'Помпушечки',
        img: 'img/item3.jpg',
        price: 2.14,
        store: 34,
        rating: 4.12,
        isNew: false,
        isPopular: false,
    },
    {
        id: 4,
        name: 'Булочки с корицей',
        img: 'img/item4.jpg',
        price: 3.20,
        store: 8,
        rating: 4.39,
        isNew: false,
        isPopular: false,
    },
    {
        id: 5,
        name: 'Кренделек-затейник',
        img: 'img/item5.jpg',
        price: 2.87,
        store: 12,
        rating: 4.69,
        isNew: false,
        isPopular: true,
    },
    {
        id: 6,
        name: 'Багет ле Франсэ',
        img: 'img/item6.jpg',
        price: 2.90,
        store: 190,
        rating: 4.02,
        isNew: false,
        isPopular: false,
    },
    {
        id: 7,
        name: 'Булочка с изюмом',
        img: 'img/item7.jpg',
        price: 3.10,
        store: 340,
        rating: 3.99,
        isNew: false,
        isPopular: true,
    },
    {
        id: 8,
        name: 'Пончики с посыпкой',
        img: 'img/item8.jpg',
        price: 3.49,
        store: 42,
        rating: 4.25,
        isNew: false,
        isPopular: false,
    },
    {
        id: 9,
        name: 'Кексик с изюмом',
        img: 'img/item9.png',
        price: 2.20,
        store: 34,
        rating: 5.0,
        isNew: false,
        isPopular: false,
    },
]